ALTER TABLE InventarioTienda ADD CONSTRAINT CK_INVENTARIOTIENDA_PRECIOV CHECK (precioV > 000.00);
ALTER TABLE InventarioTienda ADD CONSTRAINT CK_INVENTARIOTIENDA_PRECIOR CHECK (precioR > 000.00);
ALTER TABLE ARTICULO ADD CONSTRAINT CK_ARTICULO_PRECIO CHECK (precio > 000.00);
ALTER TABLE linea ADD CONSTRAINT CK_LINEA_PRECIOVENTA CHECK (precioVenta >000.00);
ALTER TABLE moneda ADD CONSTRAINT CK_MONEDA_CANTIDAD CHECK (cantidad >000.00);
ALTER TABLE inventrio ADD CONSTRAINT CK_INVENTARIO_TIPO CHECK ( tipo LIKE 'CUCHILLO' OR tipo LIKE 'ARMA' OR tipo LIKE 'SKIN');
ALTER TABLE JUGADOR ADD CONSTRAINT CK_JUGADOR_CORREO CHECK (REGEXP_LIKE(correo, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'));
ALTER TABLE MONEDA ADD CONSTRAINT CK_MONEDA_TIPODEMONEDA CHECK ( tipoDeMoneda LIKE 'VALORANTPOINT' OR tipoDeMoneda LIKE 'RADIANTSPONIT');

