/*ATRIBUTOS*/
ALTER TABLE InventarioTienda ADD CONSTRAINT CK_INVENTARIOTIENDA_PRECIOV CHECK (precioV > 000.00);
ALTER TABLE TRANSACCIONES ADD CONSTRAINT CK_TRANSACCIONES_PRECIOVENTA CHECK (precioVenta > 000.00);
ALTER TABLE monedas ADD CONSTRAINT CK_MONEDA_CANTIDAD CHECK (cantidad >000.00);
ALTER TABLE inventarios ADD CONSTRAINT CK_INVENTARIO_TIPO CHECK ( tipo LIKE 'CUCHILLO' OR tipo LIKE 'ARMA' OR tipo LIKE 'SKIN');
ALTER TABLE JUGADORES ADD CONSTRAINT CK_JUGADORES_CORREO CHECK (REGEXP_LIKE(correo, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'));
