ALTER TABLE INVENTARIOTIENDA ADD CONSTRAINT FK_INVENTARIOTIENDA_INVENTARIOS  FOREIGN KEY (ID) REFERENCES INVENTARIOS(ID);
ALTER TABLE INVENTARIOUSUARIOS ADD CONSTRAINT FK_INVENTARIOUSUARIOS_INVENTARIOS FOREIGN KEY (ID) REFERENCES INVENTARIOS(ID);
ALTER TABLE INVENTARIOUSUARIOS ADD CONSTRAINT FK_INVENTARIOUSUARIOS_JUGADORES FOREIGN KEY (JUGADOR) REFERENCES JUGADORES(IDJUGADOR);
ALTER TABLE DATOS ADD CONSTRAINT FK_DATOS_INVENTARIOTIENDA FOREIGN KEY (TIENDA) REFERENCES INVENTARIOTIENDA(ID);
ALTER TABLE TRASNSACCIONES ADD CONSTRAINT FK_TRASNSACCIONES_INVENTARIOTIENDA FOREIGN KEY (TIENDA) REFERENCES INVENTARIOTIENDA(ID);
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_HISTORIALES FOREIGN KEY (HISTORIAL) REFERENCES HISTORIALES(NUMERO);
ALTER TABLE HISTORIALES ADD CONSTRAINT FK_HISTORIALES_JUGADOR FOREIGN KEY (JUGADOR) REFERENCES JUGADORES(IDJUGADOR);
ALTER TABLE HISTORIALES ADD CONSTRAINT FK_HISTORIALES_TRASNSACCIONES FOREIGN KEY (TRASNSACCION) REFERENCES TRASNSACCIONES(IDTRASNSACCION);
ALTER TABLE COMPRAS ADD CONSTRAINT FK_COMPRAS_TRSANASACCION FOREIGN KEY (TRASNSACCION) REFERENCES TRASNSACCIONES(IDTRASNSACCION);
ALTER TABLE CARRITOS ADD CONSTRAINT FK_CARRITOS_JUGADORES FOREIGN KEY (JUGADOR) REFERENCES JUGADORES(IDJUGADOR);
ALTER TABLE CARRITOS ADD CONSTRAINT FK_CARRITOS_COMPRAS FOREIGN KEY (COMPRA) REFERENCES COMPRAS(NUMERO);
ALTER TABLE CAMBIOS ADD CONSTRAINT FK_CAMBIOS_JUGADORES FOREIGN KEY (JUGADOR) REFERENCES JUGADORES(IDJUGADOR);
ALTER TABLE CAMBIOS ADD CONSTRAINT FK_CAMBIOS_INTERCAMBIOS FOREIGN KEY (INTERCAMBIO) REFERENCES INTERCAMBIOS(NUMERO);
ALTER TABLE INTERCAMBIOS ADD CONSTRAINT FK_INTERCAMBIOS_INVENTARIOUSUARIOS FOREIGN KEY (USUARIO) REFERENCES INVENTARIOUSUARIOS (ID);
ALTER TABLE MONEDAS ADD CONSTRAINT FK_INTERCAMBIOS_JUGADOR FOREIGN KEY (JUGADOR) REFERENCES JUGADORES(IDJUGADOR);
ALTER TABLE MONEDAS ADD CONSTRAINT FK_INTERCAMBIOS_INTERCAMBIOS FOREIGN KEY (INTERCAMBIO) REFERENCES INTERCAMBIOS(NUMERO);








