--PoblarOK

INSERT INTO INVENTARIO(IDOBJETO,TIPO,NOMBRE,COLOR) VALUES('C0001','Cuchillo','Dragon',1);
INSERT INTO INVENTARIO(IDOBJETO,TIPO,NOMBRE,COLOR) VALUES('A0002','Arma','Trueno',2);
INSERT INTO INVENTARIO(IDOBJETO,TIPO,NOMBRE,COLOR) VALUES('S0003','Skin','Tiburon',3);
INSERT INTO INVENTARIOTIENDA(IDOBJETO,PRECIOV,DESCRIPCION,PRECIOR) VALUES('C0001',100.00,'Un cuchillo de dragon',175.00);
INSERT INTO INVENTARIOTIENDA(IDOBJETO,PRECIOV,DESCRIPCION,PRECIOR) VALUES('A0002',150.00,'Un arma de trueno',125.00);
INSERT INTO INVENTARIOTIENDA(IDOBJETO,PRECIOV,DESCRIPCION,PRECIOR) VALUES('S0003',50.00,'Una skin de tiburon',25.00);
INSERT INTO INVENTARIOUSUARIO(IDOBJETO,FECHADECOMPRA,FECHADEINTERCAMBIO) VALUES('C0001',TO_DATE('20-SEP-2024', 'DD-MON-YYYY'),NULL);
INSERT INTO INVENTARIOUSUARIO(IDOBJETO,FECHADECOMPRA,FECHADEINTERCAMBIO) VALUES('A0002',TO_DATE('31-DIC-2024', 'DD-MON-YYYY'),NULL);
INSERT INTO INVENTARIOUSUARIO(IDOBJETO,FECHADECOMPRA,FECHADEINTERCAMBIO) VALUES('S0003',TO_DATE('15-ABR-2024', 'DD-MON-YYYY'),NULL);
INSERT INTO LINEA(OBJETO,PRECIOVENTA) VALUES('Cuchillo',100.00);
INSERT INTO LINEA(OBJETO,PRECIOVENTA) VALUES('Arma',125.00);
INSERT INTO LINEA(OBJETO,PRECIOVENTA) VALUES('Skin',50.00);
INSERT INTO COMPRA(NUMERO,FECHA,TOTAL) VALUES('CP001',TO_DATE('20-DIC-2024', 'DD-MON-YYYY'),100.00);
INSERT INTO COMPRA(NUMERO,FECHA,TOTAL) VALUES('IN002',TO_DATE('31-DIC-2024', 'DD-MON-YYYY'),125.00);
INSERT INTO COMPRA(NUMERO,FECHA,TOTAL) VALUES('CP003',TO_DATE('15-ABR-2024', 'DD-MON-YYYY'),50.00);
INSERT INTO JUGADOR(IDJUGADOR,NICKNAME,CORREO) VALUES('U0001','JuanOK','juan256@gmail.com');
INSERT INTO JUGADOR(IDJUGADOR,NICKNAME,CORREO) VALUES('U0002','Park256','park2024@hotmail.com');
INSERT INTO JUGADOR(IDJUGADOR,NICKNAME,CORREO) VALUES('U0003','LeoPoldo','leopoldo15@yahoo.com');
INSERT INTO MONEDA(IDMONEDA,CANTIDAD,TIPODEMONEDA) VALUES('V0001',100.00,'ValorantPoint');
INSERT INTO MONEDA(IDMONEDA,CANTIDAD,TIPODEMONEDA) VALUES('R0002',125.00,'RadiantPoint');
INSERT INTO MONEDA(IDMONEDA,CANTIDAD,TIPODEMONEDA) VALUES('V0003',50.00,'ValorantPoint');
INSERT INTO INTERCAMBIO(NUMERO,OBJETO,VALOR,FECHA) VALUES('V0001','C0001',75.00,TO_DATE('20-MAY-2024', 'DD-MON-YYYY'));
INSERT INTO INTERCAMBIO(NUMERO,OBJETO,VALOR,FECHA) VALUES('R0002','A0002',125.00,TO_DATE('31-DIC-2024', 'DD-MON-YYYY'));
INSERT INTO INTERCAMBIO(NUMERO,OBJETO,VALOR,FECHA) VALUES('V0003','S0003',25.00,TO_DATE('10-JUN-2024', 'DD-MON-YYYY'));

INSERT INTO ARTICULO(IDTIENDA,IDLINEA,PRECIOVENTA) VALUES('C0001','Cuchillo',100.00);
INSERT INTO ARTICULO(IDTIENDA,IDLINEA,PRECIOVENTA) VALUES('C0002','Arma',125.00);
INSERT INTO ARTICULO(IDTIENDA,IDLINEA,PRECIOVENTA) VALUES('C0003','Skin',50.00);

INSERT INTO OBJETO(NUMERO,IDOBJETO,NOMBRE) VALUES('V0001','C0001','Dragon');
INSERT INTO OBJETO(NUMERO,IDOBJETO,NOMBRE) VALUES('V0002','C0002','Trueno');
INSERT INTO OBJETO(NUMERO,IDOBJETO,NOMBRE) VALUES('V0003','C0003','Tiburon');