ALTER TABLE Inventario ADD CONSTRAINT PK_INVENTARIO PRIMARY KEY (IDOBJETO);
ALTER TABLE INVENTARIOTIENDA ADD CONSTRAINT PK_INVENTARIOTIENDA PRIMARY KEY (IDOBJETO);
ALTER TABLE INVENTARIOUSUARIO ADD CONSTRAINT PK_INVENTARIOUSUARIO PRIMARY KEY (IDOBJETO);
ALTER TABLE LINEA ADD CONSTRAINT PK_LINEA_ID PRIMARY KEY (ID);
ALTER TABLE ARTICULO ADD CONSTRAINT PK_ARTICULO_IDTIENDA_IDLINEA PRIMARY KEY (IDTIENDA,IDLINEA);
ALTER TABLE COMPRA ADD CONSTRAINT PK_COMPRA_NUMERO PRIMARY KEY (NUMERO);
ALTER TABLE JUGADOR ADD CONSTRAINT PK_JUGADOR_IDJUGADOR PRIMARY KEY (IDJUGADOR);
ALTER TABLE MONEDA ADD CONSTRAINT PK_MONEDA_IDMONEDA PRIMARY KEY (IDMONEDA);
ALTER TABLE INTERCAMBIO ADD CONSTRAINT PK_INTERCAMBIO_NUMERO PRIMARY KEY (NUMERO);
ALTER TABLE OBJETOS ADD CONSTRAINT PK_OBJETOS_NUMERO PRIMARY KEY (NUMERO);



