--Tablas

CREATE TABLE Inventario(
    idObjeto CHAR(5) NOT NULL,
    tipo VARCHAR(8) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    color INT NOT NULL
);

CREATE TABLE InventarioTienda(
    idObjeto CHAR(5) NOT NULL,
    precioV NUMBER(5,2)NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    precioR NUMBER(5,2) NOT NULL
);

CREATE TABLE InventarioUsuario (
    idObjeto CHAR(5) NOT NULL,
    fechadecompra DATE NULL, 
    fechadeintercambio DATE NULL
);

CREATE TABLE Linea (
    objeto VARCHAR(20) NOT NULL,
    precioVenta NUMBER(5,2) NOT NULL
);

CREATE TABLE Compra (
    numero CHAR(5) NOT NULL,
    fecha DATE NOT NULL,
    total NUMBER(5,2) NOT NULL
);

CREATE TABLE Jugador (
    idJugador CHAR(5) NOT NULL,
    nickName VARCHAR(20) NOT NULL,
    correo VARCHAR(50) NOT NULL
);

CREATE TABLE Moneda (
    idMoneda CHAR(5) NOT NULL,
    cantidad NUMBER(5,2) NOT NULL,
    tipodemoneda CHAR(13) NOT NULL
);

CREATE TABLE Intercambio (
    numero CHAR(5) NOT NULL,
    objeto CHAR(5) NOT NULL,
    valor NUMBER(5,2) NOT NULL,
    fecha DATE NOT NULL
);

--PoblarOK

INSERT INTO INVENTARIO(IDOBJETO,TIPO,NOMBRE,COLOR) VALUES('C0001','Cuchillo','Dragon',1);
INSERT INTO INVENTARIO(IDOBJETO,TIPO,NOMBRE,COLOR) VALUES('A0002','Arma','Trueno',2);
INSERT INTO INVENTARIO(IDOBJETO,TIPO,NOMBRE,COLOR) VALUES('S0003','Skin','Tiburon',3);
INSERT INTO INVENTARIOTIENDA(IDOBJETO,PRECIOV,DESCRIPCION,PRECIOR) VALUES('C0001',100.00,'Un cuchillo de dragon',175.00);
INSERT INTO INVENTARIOTIENDA(IDOBJETO,PRECIOV,DESCRIPCION,PRECIOR) VALUES('A0002',150.00,'Un arma de trueno',125.00);
INSERT INTO INVENTARIOTIENDA(IDOBJETO,PRECIOV,DESCRIPCION,PRECIOR) VALUES('S0003',50.00,'Una skin de tiburon',25.00);
INSERT INTO INVENTARIOUSUARIO(IDOBJETO,FECHADECOMPRA,FECHADEINTERCAMBIO) VALUES('C0001',TO_DATE('20-SEP-2024', 'DD-MON-YYYY'),NULL); --toca mirar bien estas, nose si estan bien
INSERT INTO INVENTARIOUSUARIO(IDOBJETO,FECHADECOMPRA,FECHADEINTERCAMBIO) VALUES('A0002',TO_DATE('31-DIC-2024', 'DD-MON-YYYY'),NULL);
INSERT INTO INVENTARIOUSUARIO(IDOBJETO,FECHADECOMPRA,FECHADEINTERCAMBIO) VALUES('S0003',TO_DATE('15-ABR-2024', 'DD-MON-YYYY'),NULL);
INSERT INTO LINEA(OBJETO,PRECIOVENTA) VALUES('Cuchillo',100.00);
INSERT INTO LINEA(OBJETO,PRECIOVENTA) VALUES('Arma',125.00);
INSERT INTO LINEA(OBJETO,PRECIOVENTA) VALUES('Skin',50.00);
INSERT INTO COMPRA(NUMERO,FECHA,TOTAL) VALUES('CP001',TO_DATE('20-DIC-2024', 'DD-MON-YYYY'),100.00);
INSERT INTO COMPRA(NUMERO,FECHA,TOTAL) VALUES('IN002',TO_DATE('31-DIC-2024', 'DD-MON-YYYY'),125.00);
INSERT INTO COMPRA(NUMERO,FECHA,TOTAL) VALUES('CP003',TO_DATE('15-ABR-2024', 'DD-MON-YYYY'),50.00);
INSERT INTO JUGADOR(IDJUGADOR,NICKNAME,CORREO) VALUES('U0001','JuanOK','juan256@gmail.com');
INSERT INTO JUGADOR(IDJUGADOR,NICKNAME,CORREO) VALUES('U0002','Park256','park2024@hotmail.com');
INSERT INTO JUGADOR(IDJUGADOR,NICKNAME,CORREO) VALUES('U0003','LeoPoldo','leopoldo15@yahoo.com');
INSERT INTO MONEDA(IDMONEDA,CANTIDAD,TIPODEMONEDA) VALUES('V0001',100.00,'ValorantPoint');
INSERT INTO MONEDA(IDMONEDA,CANTIDAD,TIPODEMONEDA) VALUES('R0002',125.00,'RadiantPoint');
INSERT INTO MONEDA(IDMONEDA,CANTIDAD,TIPODEMONEDA) VALUES('V0003',50.00,'ValorantPoint');
INSERT INTO INTERCAMBIO(NUMERO,OBJETO,VALOR,FECHA) VALUES('V0001','C0001',75.00,TO_DATE('20-MAY-2024', 'DD-MON-YYYY'));
INSERT INTO INTERCAMBIO(NUMERO,OBJETO,VALOR,FECHA) VALUES('R0002','A0002',125.00,TO_DATE('31-DIC-2024', 'DD-MON-YYYY'));
INSERT INTO INTERCAMBIO(NUMERO,OBJETO,VALOR,FECHA) VALUES('V0003','S0003',25.00,TO_DATE('10-JUN-2024', 'DD-MON-YYYY'));

--PoblarNoOK

--no deja agregar los datos debido a que el tipo de dato ingresado en IDMONEDA es de tipo caracter y no numerico.
INSERT INTO MONEDA(IDMONEDA,CANTIDAD,TIPODEMONEDA) VALUES(0001,100.00,'ValorantPoint');

--XPoblar

DELETE FROM INVENTARIO;
DELETE FROM INVENTARIOTIENDA;
DELETE FROM INVENTARIOUSUARIO;
DELETE FROM LINEA;
DELETE FROM COMPRA;
DELETE FROM JUGADOR;
DELETE FROM MONEDA;
DELETE FROM INTERCAMBIO;

--XTables

SELECT codigoCategoria, COUNT(*) as articulo_count
FROM Articulo
GROUP BY codigoCategoria
ORDER BY articulo_count DESC

DROP TABLE InventarioTienda CASCADE CONSTRAINT FORCE;
DROP TABLE InventarioUsuario CASCADE CONSTRAINT FORCE;
DROP TABLE Linea CASCADE CONSTRAINT FORCE;
DROP TABLE Compra CASCADE CONSTRAINT FORCE;
DROP TABLE Jugador CASCADE CONSTRAINT FORCE;
DROP TABLE Moneda CASCADE CONSTRAINT FORCE;
DROP TABLE Intercambio CASCADE CONSTRAINT FORCE;