/*UNIQUE KEYS*/
ALTER TABLE JUGADORES ADD CONSTRAINT UK_JUGADOR_IDJUGADOR_NICKNAME_CORREO UNIQUE (IDJUGADOR,NICKNAME,CORREO);
ALTER TABLE INVENTARIOUSUARIOS ADD CONSTRAINT UK_USUARIOS_JUGADOR UNIQUE (JUGADOR);
