--XPoblar

DELETE FROM INVENTARIO;
DELETE FROM INVENTARIOTIENDA;
DELETE FROM INVENTARIOUSUARIO;
DELETE FROM LINEA;
DELETE FROM COMPRA;
DELETE FROM JUGADOR;
DELETE FROM MONEDA;
DELETE FROM INTERCAMBIO;
DELETE FROM ARTICULO;
DELETE FROM OBJETO;