--XTables

DROP TABLE Inventario CASCADE CONSTRAINT FORCE; 
DROP TABLE InventarioTienda CASCADE CONSTRAINT FORCE;
DROP TABLE InventarioUsuario CASCADE CONSTRAINT FORCE;
DROP TABLE Linea CASCADE CONSTRAINT FORCE;
DROP TABLE Compra CASCADE CONSTRAINT FORCE;
DROP TABLE Jugador CASCADE CONSTRAINT FORCE;
DROP TABLE Moneda CASCADE CONSTRAINT FORCE;
DROP TABLE Intercambio CASCADE CONSTRAINT FORCE;
DROP TABLE Articulo CASCADE CONSTRAINT FORCE;
DROP TABLE Objeto CASCADE CONSTRAINT FORCE;